import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React from 'react'
import Grid from '@mui/material/Grid';
import Header from './header'
import Class from './class';
import Footer from './footer'

const classes = [
  {
    courseName: 'CSCI 0320: Introduction to Software Engineering',
    professor: 'Tim Nelson',
    description:
      'Focuses on designing, building, testing, and maintaining systems collaboratively.',
  },
  {
    courseName: 'CSCI 0300: Fundamentals of Computer Systems',
    professor: 'Malte Schwarzkopf',
    description:
      'Covers fundamental concepts, principles, and abstractions that underlie the design and engineering of computer systems.',
  },
  {
    courseName: 'CSCI 0190: Accelerated Introduction to CS',
    professor: 'Tim Nelson',
    description:
      'A one-semester introduction to CS covering programming integrated with core data structures, algorithms, and analysis techniques.',
  },
  {
    courseName: 'CSCI 1470: Deep Learning',
    professor: 'Ritambhara Singh',
    description:
      'In this course, you will get an overview of the prominent techniques of deep learning and their applications.',
  }
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Header title='Computer Science Course Waitlists'/>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <br></br>

      <Grid container spacing={4}>
            {classes.map((course) => (
              <Class key={course.courseName} course={course} />
            ))}
      </Grid>

      <Footer title='Created by Calvin Eng' description='with minimal help from Tabitha Lynn'/>

      {/* <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main> */}
    </div>
  )
}
